version: "3.7"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    volumes: 
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  web:
    image: docker-sample
    depends_on:
      - db
    volumes:
      - ./server.js:/usr/src/app/server.js
    env_file: ./.env
    ports:
      - "8000:8080"
    
    
    
    # build: ./
    # container_name: docker-sample
    